/**
 * @file    control_scheduler.h
 * @brief   Unified bare-metal 10 ms vehicle control scheduler.
 */

#ifndef CONTROL_SCHEDULER_H
#define CONTROL_SCHEDULER_H

#include "chassis_motion.h"
#include "gray_sensor.h"
#include "gimbal_stepper.h"
#include "line_tracker.h"
#include "odometry.h"
#include "speed_pid.h"
#include "zf_common_typedef.h"

#define CONTROL_SCHEDULER_PERIOD_MS          (10U)
#define CONTROL_SCHEDULER_MANUAL_TIMEOUT_MS  (3000U)

/** @brief Exclusive scheduler modes that own or suppress wheel targets. */
typedef enum
{
    /** Dependencies are being initialized; motion is not permitted. */
    CONTROL_MODE_BOOT = 0,
    /** Outputs are forced to zero until an arm request is accepted. */
    CONTROL_MODE_DISARMED,
    /** Accepted manual wheel targets own the speed controller inputs. */
    CONTROL_MODE_MANUAL_ARMED,
    /** The high-level chassis command generator owns wheel targets. */
    CONTROL_MODE_CHASSIS_MOTION,
    /** The line tracker owns wheel targets. */
    CONTROL_MODE_LINE_FOLLOW,
    /** A safety fault holds zero output until an explicit clear succeeds. */
    CONTROL_MODE_FAULT_LATCHED,
} control_mode_enum;

/** @brief Bit flags latched by scheduler safety and input validation. */
typedef enum
{
    /** No scheduler fault is latched. */
    CONTROL_FAULT_NONE = 0x00000000U,
    /** The active-low emergency key was asserted. */
    CONTROL_FAULT_EMERGENCY_KEY = 0x00000001U,
    /** Grayscale input initialization failed. */
    CONTROL_FAULT_GRAY_INIT = 0x00000002U,
    /** A periodic grayscale sample could not be acquired. */
    CONTROL_FAULT_GRAY_SAMPLE = 0x00000004U,
    /** An encoder interval count exceeded the accepted range. */
    CONTROL_FAULT_ENCODER_RANGE = 0x00000008U,
    /** The line tracker rejected its input or entered fault. */
    CONTROL_FAULT_LINE_TRACKER = 0x00000010U,
    /** The 10 ms update was entered before its prior call completed. */
    CONTROL_FAULT_REENTRY = 0x00000020U,
    /** A chassis command started or continued without fresh IMU yaw. */
    CONTROL_FAULT_IMU_STALE = 0x00000040U,
    /** MPU6500 initialization failed before the scheduler started. */
    CONTROL_FAULT_IMU_INIT = 0x00000080U,
} control_fault_enum;

/** @brief Automatic startup attitude-reference states. */
typedef enum
{
    CONTROL_IMU_STABILITY_WAIT_STREAM = 0,
    CONTROL_IMU_STABILITY_WARMUP,
    CONTROL_IMU_STABILITY_COLLECTING,
    CONTROL_IMU_STABILITY_READY,
} control_imu_stability_enum;

/** @brief Reason the latest gimbal feedforward was not applied. */
typedef enum
{
    CONTROL_GIMBAL_REJECT_NONE = 0,
    CONTROL_GIMBAL_REJECT_NOT_READY,
    CONTROL_GIMBAL_REJECT_SOLVER,
    CONTROL_GIMBAL_REJECT_STALE,
    CONTROL_GIMBAL_REJECT_APPLY,
} control_gimbal_reject_enum;

/** @brief Coherent scheduler and control-module telemetry snapshot. */
typedef struct
{
    /** Current owner of the wheel-speed targets. */
    control_mode_enum mode;
    /** Latched OR of @ref control_fault_enum values. */
    uint32 fault_flags;
    /** Number of accepted 10 ms update entries. */
    uint32 tick_count;
    /** Number of rejected reentrant update attempts. */
    uint32 overrun_count;
    /** Sequence number of the latest received IMU angle frame. */
    uint32 imu_angle_frame_count;
    /** Scheduler ticks since the last new valid IMU frame. */
    uint16 imu_age_ticks;
    /** Latest signed left encoder interval count. */
    int16 left_count;
    /** Latest signed right encoder interval count. */
    int16 right_count;
    /** Latest wrapped IMU yaw in degrees. */
    float imu_yaw_deg;
    /** Latest continuous MPU6500 yaw in degrees. */
    float imu_yaw_continuous_deg;
    /** Roll about body +X; MPU axes must be X forward, Y left and Z up. */
    float imu_roll_deg;
    /** Pitch about body +Y; MPU axes must be X forward, Y left and Z up. */
    float imu_pitch_deg;
    /** Estimated stationary yaw drift in degrees per minute. */
    float imu_yaw_drift_deg_min;
    /** Stored manual left-wheel target in millimeters per second. */
    float manual_left_target_mm_s;
    /** Stored manual right-wheel target in millimeters per second. */
    float manual_right_target_mm_s;
    /** Latest coherent grayscale result. */
    gray_sensor_result_struct gray;
    /** Latest wheel targets generated by the line tracker. */
    line_tracker_output_struct line_output;
    /** Latest line-tracker diagnostic snapshot. */
    line_tracker_status_struct line_status;
    /** Latest high-level chassis motion snapshot. */
    chassis_motion_status_struct chassis_motion;
    /** Latest dual-wheel speed controller snapshot. */
    speed_pid_status_struct speed;
    /** Latest fused odometry snapshot. */
    odometry_state_struct odometry;
    /** Latest two-axis gimbal controller snapshot. */
    gimbal_stepper_status_struct gimbal;
    /** Latest geometric feedforward inverse solution. */
    gimbal_feedforward_solution_struct gimbal_feedforward;
    /** Number of accepted real-time feedforward updates. */
    uint32 gimbal_feedforward_count;
    /** Number of computed feedforward updates that were rejected. */
    uint32 gimbal_feedforward_reject_count;
    /** Number of feedforward updates rejected specifically as stale. */
    uint32 gimbal_feedforward_stale_count;
    /** Scheduler ticks crossed by the latest foreground solve. */
    uint16 gimbal_feedforward_solve_ticks;
    /** Latest startup attitude-reference state. */
    control_imu_stability_enum imu_stability_state;
    /** Latest feedforward rejection reason. */
    control_gimbal_reject_enum gimbal_feedforward_reject_reason;
    /** Nonzero after scheduler dependency initialization. */
    uint8 initialized;
    /** Nonzero after the unique periodic source starts. */
    uint8 started;
    /** Nonzero when the IMU has supplied a valid yaw value. */
    uint8 imu_valid;
    /** Nonzero while the latest valid IMU frame is within its age limit. */
    uint8 imu_fresh;
    /** Nonzero after the startup attitude reference is stable and installed. */
    uint8 imu_ready;
    /** Startup stability progress from 0 through 100 percent. */
    uint8 imu_stability_progress;
    /** Nonzero after both gimbal axes were manually referenced. */
    uint8 gimbal_calibrated;
    /** Nonzero when the latest real-time feedforward command was accepted. */
    uint8 gimbal_feedforward_valid;
} control_scheduler_status_struct;

/**
 * @brief Initialize all scheduler dependencies in a stopped state.
 * @return ZF_TRUE when mandatory hardware initialization succeeds.
 */
uint8 control_scheduler_init(void);

/**
 * @brief Start the scheduler's unique 10 ms PIT source.
 * @return ZF_TRUE when the periodic source was started.
 */
uint8 control_scheduler_start(void);

/**
 * @brief Execute one complete 10 ms control pipeline.
 * @note Call from exactly one periodic context.
 */
void control_scheduler_update_10ms(void);

/** @brief Run deferred non-real-time actions from foreground context. */
void control_scheduler_process_foreground(void);

/** @brief Queue an arm request for the next scheduler tick. */
void control_scheduler_request_arm(void);

/** @brief Queue a disarm request for the next scheduler tick. */
void control_scheduler_request_disarm(void);

/** @brief Queue a line-follow start request for the next scheduler tick. */
void control_scheduler_request_line_start(void);

/** @brief Queue a line-follow stop request for the next scheduler tick. */
void control_scheduler_request_line_stop(void);

/** @brief Queue a latched-fault clear request for the next scheduler tick. */
void control_scheduler_request_fault_clear(void);

/**
 * @brief Queue bounded manual wheel targets for the next scheduler tick.
 * @param left_mm_s Left wheel target in millimeters per second.
 * @param right_mm_s Right wheel target in millimeters per second.
 * @return ZF_TRUE when both targets are valid.
 */
uint8 control_scheduler_request_manual_target(
    float left_mm_s,
    float right_mm_s);

/**
 * @brief Submit a high-level signed distance command.
 * @param distance_mm Positive for forward and negative for reverse distance.
 * @param max_speed_mm_s Positive maximum center speed.
 * @return ZF_TRUE when request values are valid.
 */
uint8 control_scheduler_request_chassis_motion_distance(
    float distance_mm,
    float max_speed_mm_s);

/**
 * @brief Submit a high-level timed signed-speed command.
 * @param speed_mm_s Positive for forward and negative for reverse speed.
 * @param duration_ms Command duration.
 * @return ZF_TRUE when request values are valid.
 */
uint8 control_scheduler_request_chassis_motion_timed(
    float speed_mm_s,
    uint32 duration_ms);

/**
 * @brief Submit a high-level relative heading-turn command.
 * @param angle_deg Relative angle from -360 to 360 degrees, excluding zero.
 *                  Positive turns left and negative turns right.
 * @param max_angular_speed_deg_s Positive maximum angular speed.
 * @return ZF_TRUE when request values are valid.
 */
uint8 control_scheduler_request_chassis_motion_turn_relative(
    float angle_deg,
    float max_angular_speed_deg_s);

/**
 * @brief Submit a request to smoothly cancel the active chassis command.
 */
void control_scheduler_request_chassis_motion_cancel(void);

/**
 * @brief Submit a request to select one configured chassis PID parameter group.
 * @param profile_id Profile identifier from 0 to 3.
 * @return ZF_TRUE when the profile identifier is valid.
 */
uint8 control_scheduler_request_chassis_motion_pid_profile(uint8 profile_id);

/**
 * @brief Copy one coherent scheduler telemetry snapshot.
 * @param status Destination status structure.
 */
void control_scheduler_get_status(control_scheduler_status_struct *status);

/** @brief Return the current 10 ms scheduler tick count atomically. */
uint32 control_scheduler_get_tick_count(void);

#endif
