/**
 * @file    drive_geometry.h
 * @brief   Shared differential-drive geometry and calibration constants.
 */

#ifndef DRIVE_GEOMETRY_H
#define DRIVE_GEOMETRY_H

/** Circle ratio used by the drive calculations. */
#define DRIVE_PI                           (3.14159265F)
/** Encoder counts generated by one wheel revolution. */
#define DRIVE_ENCODER_COUNTS_PER_REV       (10250U)

/** Calibrated left wheel diameter in millimeters. */
#define DRIVE_LEFT_WHEEL_DIAMETER_MM       (48.0F)
/** Calibrated right wheel diameter in millimeters. */
#define DRIVE_RIGHT_WHEEL_DIAMETER_MM      (48.0F)
/** Distance between wheel contact-line centers in millimeters. */
#define DRIVE_TRACK_WIDTH_MM               (129.0F)

/** Left wheel travel in millimeters per encoder count. */
#define DRIVE_LEFT_MM_PER_COUNT            \
    ((DRIVE_PI * DRIVE_LEFT_WHEEL_DIAMETER_MM) \
        / (float)DRIVE_ENCODER_COUNTS_PER_REV)
/** Right wheel travel in millimeters per encoder count. */
#define DRIVE_RIGHT_MM_PER_COUNT           \
    ((DRIVE_PI * DRIVE_RIGHT_WHEEL_DIAMETER_MM) \
        / (float)DRIVE_ENCODER_COUNTS_PER_REV)

/** Encoder heading weight in the range 0 through 1. */
#define DRIVE_ODOMETRY_ENCODER_WEIGHT      (0.98F)
/** IMU heading-correction weight complementary to the encoder weight. */
#define DRIVE_ODOMETRY_IMU_WEIGHT          \
    (1.0F - DRIVE_ODOMETRY_ENCODER_WEIGHT)

#endif
