/**
 * @file    line_tracker.h
 * @brief   Pure eight-channel line tracking target generator.
 */

#ifndef LINE_TRACKER_H
#define LINE_TRACKER_H

#include "gray_sensor.h"
#include "zf_common_typedef.h"

#define LINE_TRACKER_SPEED_BAND_COUNT    (5U)
#define LINE_TRACKER_UPDATE_PERIOD_MS    (10U)

/** @brief Line tracker operating states. */
typedef enum
{
    /** A valid line sample is generating forward PID targets. */
    LINE_TRACKER_STATE_TRACKING = 0,
    /** Lost-line search is following the initial forward arc. */
    LINE_TRACKER_STATE_LOST_ARC,
    /** Lost-line search is pivoting after the arc period. */
    LINE_TRACKER_STATE_LOST_PIVOT,
    /** All channels are active and both wheel targets are zero. */
    LINE_TRACKER_STATE_ALL_ACTIVE,
    /** A latched input, configuration or search-timeout fault. */
    LINE_TRACKER_STATE_FAULT,
} line_tracker_state_enum;

/** @brief Last known line direction used by lost-line search. */
typedef enum
{
    /** Search left; represented by the signed value -1. */
    LINE_TRACKER_DIRECTION_LEFT = -1,
    /** No known direction; represented by zero. */
    LINE_TRACKER_DIRECTION_NONE = 0,
    /** Search right; represented by the signed value 1. */
    LINE_TRACKER_DIRECTION_RIGHT = 1,
} line_tracker_direction_enum;

/** @brief Runtime parameters for tracking PID and lost-line behavior. */
typedef struct
{
    /** Forward speed for each absolute-error band, in mm/s. */
    float base_speed_mm_s[LINE_TRACKER_SPEED_BAND_COUNT];
    /** Proportional correction gain in mm/s per normalized error. */
    float pid_kp[LINE_TRACKER_SPEED_BAND_COUNT];
    /**
     * Integral-output gain applied with the 10 ms update period.
     * Units are mm/s per normalized-error second; must be nonnegative.
     */
    float pid_ki;
    /**
     * Derivative-output gain applied to normalized error per second.
     * Units are millimeters per normalized error; must be nonnegative.
     */
    float pid_kd;
    /** Nonnegative absolute integral-output limit in mm/s. */
    float pid_integral_limit_mm_s;
    /** Derivative low-pass coefficient in the range 0 through 1. */
    float pid_derivative_filter_alpha;
    /** Positive absolute wheel-speed target limit in mm/s. */
    float max_target_mm_s;
    /** Nonnegative absolute differential correction limit in mm/s. */
    float max_correction_mm_s;
    /** Nonnegative outer arc speed in mm/s; greater than inner speed. */
    float arc_outer_speed_mm_s;
    /** Nonnegative inner arc speed in mm/s. */
    float arc_inner_speed_mm_s;
    /** Nonnegative pivot speed magnitude in mm/s. */
    float pivot_speed_mm_s;
    /** Consecutive lost samples required before search; must be nonzero. */
    uint16 lost_debounce_samples;
    /** Consecutive valid samples required to reacquire; must be nonzero. */
    uint16 reacquire_samples;
    /** Initial arc duration in 10 ms samples; must be nonzero. */
    uint16 arc_duration_samples;
    /** Total search limit in 10 ms samples; must exceed arc duration. */
    uint16 search_timeout_samples;
    /** Fallback search direction; must be LEFT or RIGHT. */
    line_tracker_direction_enum default_search_direction;
} line_tracker_config_struct;

/** @brief Signed wheel-speed targets generated by the tracker. */
typedef struct
{
    /** Signed left wheel target in millimeters per second. */
    float left_target_mm_s;
    /** Signed right wheel target in millimeters per second. */
    float right_target_mm_s;
} line_tracker_output_struct;

/** @brief Observable line tracker state for diagnostics and tests. */
typedef struct
{
    /** Current tracking, search, stop or fault state. */
    line_tracker_state_enum state;
    /** Classification of the latest accepted grayscale sample. */
    gray_sensor_status_enum sensor_status;
    /** Direction selected for the current or next lost-line search. */
    line_tracker_direction_enum search_direction;
    /** Latest sensor deviation from -3.5 through 3.5 channel indexes. */
    float deviation;
    /** Deviation scaled to the controller range -5 through 5. */
    float normalized_deviation;
    /** Most recent valid sensor deviation in channel-index units. */
    float last_valid_deviation;
    /** Applied signed differential correction before wheel clamping. */
    float correction_mm_s;
    /** Current bounded integral contribution in mm/s. */
    float pid_integral_mm_s;
    /** Current filtered normalized-error derivative per second. */
    float pid_filtered_derivative;
    /** Current signed left target in millimeters per second. */
    float left_target_mm_s;
    /** Current signed right target in millimeters per second. */
    float right_target_mm_s;
    /** Consecutive lost samples, capped at the debounce threshold. */
    uint16 lost_samples;
    /** Consecutive valid samples, capped at the reacquire threshold. */
    uint16 valid_samples;
    /** Consecutive all-active samples, saturating at UINT16_MAX. */
    uint16 all_active_samples;
    /** Elapsed search samples, bounded by the configured timeout. */
    uint16 search_samples;
    /** Selected base-speed and gain band from 0 through 4. */
    uint8 speed_band;
    /** Nonzero when PID correction or a wheel target is clamped. */
    uint8 output_limited;
} line_tracker_status_struct;

/**
 * @brief Initialize the tracker with caller settings or built-in defaults.
 * @param config Optional configuration; NULL selects the built-in defaults.
 * @note Invalid caller settings leave the tracker in a latched fault state.
 */
void line_tracker_init(const line_tracker_config_struct *config);

/**
 * @brief Clear tracking history, counters and generated wheel targets.
 * @note Preserves the active configuration and initialization state.
 */
void line_tracker_reset(void);

/**
 * @brief Validate and atomically replace the runtime configuration.
 * @param config Complete configuration to apply; must not be NULL.
 * @return ZF_TRUE when every field is valid and the config was applied.
 * @note A successful update clears PID history but preserves other status.
 */
uint8 line_tracker_set_config(
    const line_tracker_config_struct *config);

/**
 * @brief Convert one coherent grayscale result into bounded wheel targets.
 * @param sensor Result produced by gray_sensor_sample() or calculation.
 * @param output Destination wheel targets; must not be NULL.
 * @return ZF_TRUE while operating, or ZF_FALSE after a latched fault.
 * @note Call from exactly one periodic context.
 * @note Invalid input or search timeout latches zero-output fault state.
 */
uint8 line_tracker_update(
    const gray_sensor_result_struct *sensor,
    line_tracker_output_struct *output);

/**
 * @brief Copy one interrupt-coherent tracker status snapshot.
 * @param status Destination status; NULL causes no operation.
 */
void line_tracker_get_status(line_tracker_status_struct *status);

#endif
